### PR TITLE
fix: reuse commit-message for in-action commit

### PR DESCRIPTION
**Pull request by yajo**
If the repo uses some kind of commit message linting, such as a pre-commit hook that implements commitizen, it will be able to still do the commit without linter violations.

### CODE REVIEW

**Comment by mhils** [comment]
Would `--no-verify` work for you as well?

**Comment by yajo** [comment]
Yes, too.

**Comment by mhils** [comment]
In this case I would much prefer to use --no-verify, then it works out of the box and does not require configuration.

**Review by mhils — APPROVED** [review]
Thanks! 🍰

**Pull request merged**
